name: Deploy SoftlyPlease API to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install validator deps
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema

      - name: Validate artifact index
        working-directory: softlyplease
        run: |
          python tools/verify_index.py artifact_index.json schemas/artifact_index.schema.json

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2473170F413A4950A433A8AA9DEF77D5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8E39FD908B014CD59E26DD8ADC9D5D21 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6E0FEE592B6A4F85A40F64D52C27B01C }}

      - name: Deploy Python API (Oryx build on App Service)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'soft-shadow'
          slot-name: 'Production'
          package: 'softlyplease'

