name: Deploy rhino.compute to IIS (self-hosted)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download rhino.compute payload from private release
        if: env.RC_RELEASE_URL
        shell: pwsh
        env:
          RC_RELEASE_URL: ${{ secrets.RC_RELEASE_URL }}
          RC_RELEASE_TOKEN: ${{ secrets.RC_RELEASE_TOKEN }}
        run: |
          if (-not $env:RC_RELEASE_URL) { exit 0 }
          $hdr=@{ Authorization = "token $env:RC_RELEASE_TOKEN" }
          Invoke-WebRequest -Headers $hdr -Uri $env:RC_RELEASE_URL -OutFile compute_payload.zip
          Expand-Archive -Path compute_payload.zip -DestinationPath deploy/site -Force
      - name: Validate payload
        shell: pwsh
        run: |
          if (!(Test-Path "deploy/site/web.config")) { throw "web.config missing under deploy/site" }
          if (!(Test-Path "deploy/site/rhino.compute.exe")) { throw "rhino.compute.exe missing under deploy/site" }
      - name: Zip site
        shell: pwsh
        run: Compress-Archive -Path deploy/site/* -DestinationPath site.zip -Force
      - uses: actions/upload-artifact@v4
        with:
          name: compute-site
          path: site.zip
          if-no-files-found: error

  deploy:
    runs-on: [self-hosted, windows]
    needs: package
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: compute-site
          path: .
      - name: Deploy to IIS
        shell: pwsh
        env:
          IIS_SITE_PATH: ${{ secrets.IIS_SITE_PATH }}
          IIS_APP_POOL:  ${{ secrets.IIS_APP_POOL }}
          HEALTH_URL:    ${{ secrets.IIS_HEALTH_URL }}
        run: |
          if (-not $env:IIS_SITE_PATH -or -not $env:IIS_APP_POOL) { throw "Set repo secrets IIS_SITE_PATH and IIS_APP_POOL" }
          $script = Join-Path $pwd 'deploy/Deploy-IIS.ps1'
          if (!(Test-Path $script)) { throw "deploy/Deploy-IIS.ps1 missing" }
          & $script -ZipPath (Join-Path $pwd 'site.zip') -SitePath $env:IIS_SITE_PATH -AppPool $env:IIS_APP_POOL -HealthUrl $env:HEALTH_URL -HealthTimeoutSec 30

