name: Rhino Docs Index

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # weekly Mondays 06:00 UTC

jobs:
  index-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      - name: Run indexer (bounded)
        run: |
          mkdir -p data
          python3 scripts/rhino_docs_indexer.py --max-pages 150 --out data/rhino_docs_index.json
      - name: Upload index artifact
        uses: actions/upload-artifact@v4
        with:
          name: rhino-docs-index
          path: data/rhino_docs_index.json
